/**
 * kseb_branches.js
 * Comprehensive directory of 778 Kerala State Electricity Board (KSEB)
 * Electrical Sections & Branches across all districts in Kerala.
 */

const KSEB_BRANCHES = [
  "Fort", "Manacaud", "Thiruvallam", "Poonthura", "Puthenchantha", "Cantonment",
  "Thycaud", "Vellayamballam", "Vattiyoorkavu", "Peroorkada", "Kudappanakkunnu",
  "Kachani (RAPDRP)", "Thirumala", "Poojappura", "Karamana", "Pappanamcode (RAPDRP)",
  "Mangalapuram", "Kaniyapuram", "Pothencode", "Kazhakuttam", "Kulathoor",
  "Sreekariyam", "Ulloor", "Kesavadasapuram", "Nalanchira", "Vattappara",
  "Beach", "Sreevaraham", "Pettah", "Attingal", "Avanavancherry", "Kallambalam",
  "Palachira", "Kadakkavoor", "Vakkom", "Chirayinkeezhu", "Varkala", "Kedakulam",
  "Edava", "Kilimannoor", "Madavoor", "Nagaroor", "Pallickal", "Nedumangad",
  "Chullimanoor", "Vithura", "Palode", "Uzhamalakkal", "Peringamala", "Tholicode",
  "Venjaramood", "Kanyakulangara", "Kallara", "Vamanapuram", "Peyad", "Vellanad",
  "Aryanad", "Malayinkeezh", "Kattakada", "Maranalloor", "Poovachal",
  "Neyyattinkara", "Udiyankulangara", "Marayamuttom", "Kamukinkode", "Parassala",
  "Uchakkada", "Vellarada", "Amboori", "Kunnathukal", "Puzhikunnu", "Balaramapuram",
  "Kottukal", "Nemom", "Kalliyoor", "Vizhinjam", "Poovar", "Kanjiramkulam",
  "Kadappakkada", "Olai", "Sakthikulangara", "Thankasserry", "Perinad",
  "Kilikolloor", "Kanjiramkuzhy", "Pallimukku", "Ayathil", "Oachira",
  "Karunagappally(N)", "Karunagappally(S)", "Manappally Ottasekharamangalam", "Chavara",
  "Thevalakkara", "Panmana", "Sasthamcotta", "Sooranad", "Mynagappally",
  "Chathannoor", "Parippally", "Paravoor", "Poothakulam", "Kottiyam",
  "Kannanalloor", "Mayyanad", "Kundara", "Ezhukone", "East kallada", "Veliyam",
  "Oyoor", "Perumpuzha", "Nallila", "Kottarakkara (West)", "Kulakkada", "Puthur",
  "Kottarakkara East", "Pattazhy", "Chengamanadu", "Ayoor", "Valakom",
  "Chadayamangalam", "Punalur", "Thenmala", "Karavaloor", "Pathanapuram",
  "Piravanthoor", "Vilakkudi", "Anchal (East)", "Anchal West", "Karukone",
  "Kulathupuzha", "Chithara", "Kadakkal", "Pathanamthitta", "Kumbazha", "Konni",
  "Vakayar", "Vadasserikkara", "Kakkad", "Ranni Perunad", "Ranni (South)",
  "Vechoochira", "Ranni (North)", "Kozhenchery", "Ayiroor", "Aranmula", "Adoor",
  "Kaippattoor", "Enathu", "Ezhamkulam", "Kalanjoor", "Kadambanad",
  "Thengamom- Pallickal", "Pandalam", "Kulanada", "Elavumthitta", "Thiruvalla",
  "Thottabhagom", "Kumbanad", "Manipuzha", "Kadapra", "Vennikulam", "Mallappally",
  "Vaipur", "Pallom", "Punja Pallom", "Nattakam", "Gandhinagar", "Aymanam",
  "Kumarakam", "Manarcad", "Ayarkunnam", "Puthuppally", "Meenadom",
  "Kottayam (Central)", "Kottayam (East)", "Changanachery", "Kurichy", "Thengana",
  "Vakathanam", "Thrikkodithanam", "Karukachal", "Manimala", "Pathanad",
  "Vaikkom", "Chempu", "Thalayazham", "Ettumanur", "Athirampuzha", "Kuruppanthara",
  "Neendoor", "Kuravilangad", "Kaduthuruthy", "Thalayolaparambu", "Peruva", "Pala",
  "Kidangoor", "Paika", "Bharananganam", "Marangattupally", "Ramapuram",
  "Kollappally", "Erattupetta", "Poonjar", "Pinnakkanad", "Teekoy", "Ponkunnam",
  "Vazhoor", "Pallickathode", "Pampady", "Kooroppada", "Kanjirappally", "Erumely",
  "Mundakkayam", "Koottikkal", "Parathode", "Alappuzha North", "Alappuzha Town",
  "Alappuzha South", "Punnapra", "Ambalappuzha", "Thakazhy", "Edathua",
  "Chambakulam", "Mankombu", "Kidangara", "Kainakari", "Cherthala", "Cherthala East",
  "Thaneer Mukkom", "Poochakkal", "Arookutty", "Aroor", "Kuthiathode",
  "Pattanakadu", "Arthungal", "Muhamma", "S.L.Puram", "Kalavoor", "Pathirappally",
  "Mavelikkara", "Thattarambalam", "Charummood", "Kattanam", "Nooranad",
  "Vallikunnam", "Chenganoor", "Kallissery", "Mulakuzha", "Kollakadavu",
  "Chennithala", "Mannar", "Cheppad", "Kayamkulam East", "Krishnapuram",
  "Kayamkulam West", "Muthukulam", "Harippad", "Pallippad", "Karuvatta",
  "Karthikappally", "Arattupuzha", "Kattapana", "Erattayar", "Thookkupalam",
  "Nedumkandam", "Udumbanchola", "Vandanmedu", "Anakkara", "Kanchiyar", "Painavu",
  "Kanjikuzhy", "Murikkassery", "Peerumade", "Upputhura", "Vandiperiyar",
  "Peruvanthanam", "Kumily", "Chithirapuram", "Rajakumary", "Marayoor", "Adimali",
  "Kambilikandom", "Rajakkad", "Thodupuzha-I", "Moolamattom", "Purappuzha",
  "Thodupuzha-II", "Alakode Thodupuzha (RAPDRP)", "Karimannur", "Vannapuram",
  "College", "Thevara", "Girinagar", "Palarivattom", "Edappally", "Kaloor",
  "Vennala", "Vaduthala", "Cheranellore", "Thripunithura", "Udayamperoor",
  "Maradu", "Eroor", "Panangad", "Chottanikkara", "Mulamthuruthy-Renamed Amballoor",
  "Arakkunnam", "Mulanthuruthy", "Kolencherry", "Puthencruz", "Thiruvaniyoor",
  "Vyttila", "Thrikkakkara", "Thrikkakkara West", "Palluruthy", "Kannamali",
  "Kumbalangi", "Edakochi (RAPDRP)", "Thoppumpady", "Mattancherry", "Fort Cochin",
  "Vypin", "Njarackkal", "Aluva ( Town)", "Aluva(North)", "Edayar(Muppathadom)",
  "Aluva(West)", "Chowara", "Athani", "Kalamassery", "Eloor",
  "Thevakkal", "Kunnukara", "Kalady", "Thuvaroor", "Manjapra", "Malayattoor",
  "Kanjoor", "Angamaly", "Parakadavu", "Karakutty", "Mookannur", "Perumbavoor",
  "Vazhakulam", "Okkal", "Vengola", "Kizhakkambalam", "Edathala", "Pattimattam",
  "Kurupampady", "Vengoor", "Koovappady", "Moovattupuzha-I", "Pothanikad",
  "Kalloorkad", "Manjalloor", "Moovattupuzha-II", "Velloorkunnam", "Valayanchirangara",
  "Piravom", "Koothattukulam", "Pampakuda", "Kothamangalam-I", "Keerampara",
  "Kothamangalam-II", "Nellikuzhy", "Varapuzha", "Ezhikkara", "Alangad",
  "North Parur", "Cherai", "Mannam", "Chendamangalam", "Vadakkekkara",
  "Moothakunnam", "Cherpu", "Karuvannur", "Parappookara", "Chirakkal", "Kattoor",
  "Irinjalakuda- I", "Kombodinjamakkal", "Vellangallur", "Irinjalakuda-II",
  "Puthenchira", "Annamanada", "Koratty", "Meloor", "Chalakkudy", "Pariyaram",
  "Vellikulangara", "Kuttichira", "Kodakara", "Puthukkad", "Varandarappally",
  "Kuzhoor", "Mala", "Puthenvelikkara", "Kaipamangalam", "Mathilakom",
  "Perinjanam", "Kodungalloor-I", "Kodungalloor- II", "Erayad", "Peringottukara",
  "Thalikulam", "Thriparayar", "Valappad", "Koorkancherry", "Ammadom",
  "Kuriachira", "Ollur", "Marathakara", "Mannuthy", "Pattikad", "Nadathara",
  "Ayyanthole", "Arimboor", "Viyur", "R.V.Puram", "Mulamkunnathukavu", "Muthuvara",
  "Parappur", "Pavaratty", "Vadanappally", "Kandassankadavu", "Vengidange",
  "Kundannur", "Desamangalam", "Cheruthuruthy", "Vadakkancherry", "Punnamparambu",
  "Medical College(Peringandoor)", "Chelakara", "Pazhayannur", "Thiruvillwamala",
  "Kecheri", "Mundur", "Koonamoochy", "Guruvayoor", "Chavakkad", "Kunnamkulam",
  "Pazhanji", "Perumbivilavu", "Big Bazar", "Punnayoorkulam", "Sulthanpet",
  "BigBazar", "Melamuri", "Kalpathy", "Olavakkode", "Malampuzha", "Kanjikode",
  "Walayar", "Elapully", "Marutharoad", "Parali", "Pathirippala",
  "Lakkidi- Koottupatha", "Kongad", "Kadambazhippuram", "Chittur",
  "Kozhinjampara", "Velanthavalam", "Tattamangalam", "Koduvayur", "Pudunagaram",
  "Vandithavalam", "Kollengode", "Muthalamada", "Nelliampathy", "Vadavannur",
  "Alathur", "Padoor", "Kunnissery", "Puthucode", "Nemmara", "Kayaradi",
  "Mudappallur", "Vadakkenchery", "Kizhakkancherry", "Kuzhalmannam", "Kottayi",
  "Peringottukurissy", "Kuthannur", "Mannarkkad", "Kumaramputhur", "Alanallur",
  "Tachampara", "Kanjirapuzha", "Agali", "Kottathara", "Shoranur", "Ottappalam",
  "Vaniyamkulam", "Ambalappara", "Cherpulassery", "Kothakurussy",
  "Sreekrishnapuram", "Pengattiri", "Pattambi", "Vallapuzha", "Koppam",
  "Vilayur", "Thiruvegapura", "Muthuthala", "Ongallur", "Thrithala", "Chalissery",
  "Peringode", "Padinjarangadi", "Koottupatha", "Kumbidi", "Manjeri(South)",
  "Manjeri(North)", "Anakkayam", "Thrikkalangode", "Malappuram", "Chattiparamba",
  "Malappuram (West)", "Velluvambram", "Perinthalmanna", "Thazhecode",
  "Angadippuram", "Pattikkad Chungam", "Pulamanthole", "Makkaraparamba",
  "Puzhakkattiri", "Mankada", "Kolathur", "Kondotty", "Karad", "Pulikkal",
  "Kunnumpuram (AR Nagar)", "Areacode", "Keezhuparamba", "Edavannappara",
  "Mundakkulam", "Kizzhissery", "Nilambur", "Akambadam", "Pookottumpadam",
  "Karulai", "Edakkara", "Chungathara", "Vazhikkadavu", "Pothukallu", "Moothedam",
  "Kalikavu", "Karuvarakundu", "Melattoor", "Wandoor", "Edavanna", "Mampad",
  "Vaniyambalam", "Thiruvali", "Pandikkad", "Tuvvur", "Tirur(East)", "Tirur(West)",
  "Ponmundam", "Thanalur", "Thanur", "Thanur (East)", "Alathiyur", "Vettom",
  "Thirunavaya", "Purathur", "Kadungathukundu", "Puthenathani", "Kadampuzha",
  "Thuvvakkad (puthenathaniSouth)", "Valancheri", "Edayoor", "Kuttipuram",
  "Ponnani", "Thavanur", "Purangu", "Ezhuvathurithy", "Perumpadappu - Eramangalam",
  "Edappal", "Kandanakom-Kalady", "Changaramkulam", "Kottakkal", "Indianoor",
  "Othukungal", "Vengara", "Oorakam", "Parappanangadi", "Vallikunnu", "Chelari",
  "Tirurangadi", "Thalappara", "Edarikode", "Venniyoor", "Quilandi (South)",
  "Quilandi (North)", "Moodadi", "Melady", "Thikkody", "Maniyoor",
  "Vatakara (South)", "Vatakara (North)", "Vadakara Beach", "Ayyancherry",
  "Thiruvallur", "Muttungal", "Azhiyoor", "Orkkatteri", "Nadapuram", "Edacherri",
  "Thuneri", "Parappupara", "Parakkadavu", "Kuttiyadi", "Kakkattil",
  "Thottilpalam", "Perambra", "Areekkulam", "Chakkittapara ( Peruvannamoozhi)",
  "Naduvannur", "Meppayoor", "Perambra (North)", "Pottammal", "Kovoor", "Mavoor",
  "Eranhikkal", "Vellimadukunnu", "WestHill", "Kakkodi", "Chelannur", "Narikkuni",
  "Karaparamba", "Nadakkave", "Central", "Feroke", "Kadalundi",
  "Ramanattukara", "Kallai", "Beypur", "Areekkad", "Mankavu", "Perumanna",
  "Pantheerankavu", "Kunnamangalam", "Mukkam", "Kattangal", "Thiruvambadi",
  "Koompara", "Omassery", "Pannikkode", "Koodaranji", "Thamarassery",
  "Puthuppady", "Koduvally", "Kodencheri", "Balussery", "Koottalida", "Kakkoor",
  "Koorachundu", "Unnikulam", "Atholi", "Kalpetta", "Vythiri", "Meppadi",
  "Muttil", "Sultan Bathery", "Sultan Bathery( West)", "Ambalavayal",
  "Meenangadi", "Mananthavady", "Korum", "Thavinhal", "Vellamunda", "Kattikulam",
  "Panamaram", "Kambalakkad", "Pulpally", "Padinjarethara", "Padichira",
  "Payyanur", "Ramanthali", "Kunhimangalam", "Vellur", "Karivellur",
  "Padiyottuchal", "Cherupuzha", "Payyangadi", "Madai", "Mathamangalam",
  "Thaliparamba", "Pariyaram", "Dharmassala", "Chapparappadavu", "Karimbam",
  "Alakkode", "Karthikapuram", "Sreekantapuram", "Chemperi", "Irikkur", "Payyavur",
  "Iritty", "Vallithode", "Kelakom", "Ulikkal", "Edoor", "Mattannur", "Thondiyil",
  "Kakkayangad", "Sivapuram", "Kannur", "Pallikunnu", "Burnasseri", "Chovva",
  "Thayyil", "Kadachira", "Peralassery", "Valapattanam", "Mayyil", "Kolachery",
  "Eaichur", "Chakkarakallu", "Chalode", "Pappinisseri", "Cherukunnu", "Azheekode",
  "Thalassery ( South)", "Thalassery ( North)", "Kodiyeri", "Koothuparamba",
  "Kolayad", "Kathiroor", "Pattiyam", "Panoor", "Chokli", "Peringathur (RAPDRP)",
  "Parad", "Pinarayi", "Dharmadom", "Vengad", "Kasargode", "Nellikunnu",
  "Kumbala", "Cherkala", "Badiadka", "Seethangoli", "Mulleria", "Chattanchal",
  "Perla", "Uppala", "Paivalika", "Manjeswar", "Vorkady", "Udma", "Kuttikole",
  "Kanhangad", "Chittari", "Mavungal", "Rajapuram", "Periya Bazar", "Neeleswar",
  "Nallompuzha", "Bhimanadi", "Choyamkode", "Balamthode", "Padannakkad",
  "Pilicode", "Thrikaripur", "Kayyur", "Padanna"
];

// Helper to get unique sorted list
function getUniqueKsebBranches() {
  return Array.from(new Set(KSEB_BRANCHES)).sort((a, b) => a.localeCompare(b));
}

// Populate HTML datalist element
function populateKsebDatalist(datalistId) {
  const el = document.getElementById(datalistId);
  if (!el) return;
  const branches = getUniqueKsebBranches();
  el.innerHTML = branches.map(b => `<option value="${b}"></option>`).join('');
}
